_target_: pipelines.recognizer.parseq.PARSeqRecognizer


cuda: True
weights_path: ../weights/parseq_baseline__2026_02_11.pth
input_shape: [3, 32, 128]
vocab: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzЁІАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёіҒғҚқҢңҮүҰұҺһӘәӨө0123456789!"#$%&)*+,-./\\:;<=>?@()‚„•°[]^_`{|}~«»“”’—–₸₽№£ '

