_target_: "src.models.crnn.CRNNModel"

backbone: 
  name: 'mobileone_s4'
  pretrained: true

vocab: ${data.vocab}
timesteps: ${data.timesteps}
input_shape: ${data.input_shape}
pretrained: true
cuda: true
weights_path: null
decoder: 'lstm' # can be custom 'lstm', 'gru'
dropout: 0.3

filter_ctc: false
frames: 3

# compile model for faster training with pytorch 2.0
compile: false

optimizer:
  _target_: "torch.optim.AdamW"
  _partial_: true
  lr: 1e-3
  weight_decay: 5e-4
  betas:
    - 0.9
    - 0.997
  eps: 1e-6

scheduler:
  _target_: "src.lit_modules.schedulers.ChainCyclicLR"
  _partial_: true
  lr_min: 5e-5
  lr_max: 1e-3
  T0: 1000
  warmup_steps: 200
  scale_factor: 0.7